# Generated by Django 5.0.6 on 2024-05-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='message',
            new_name='content',
        ),
    ]
